### ISSUE TITLE
compiler not saving

### ISSUE THREAD

**Issue by dpx666** [royqh1979/Dev-CPP#168]
im using non compiler versiono. after i set up my compiler(gcc v8) 
when i close program then repoen the compiler setting not save have to redo

**Comment by dpx666** [comment]
dw working though there is alot of error pop up while im typing like it say compiler executable 'g++.exe' not exists
when i press enter that error sometime pop up alot

**Comment by dpx666** [comment]
i really like what u done just annoying pop up error when typing and just now when i close i cant close it says index out of bounds error have to end process in task manager

**Comment by royqh1979** [comment]
en, this happens when your gcc folder is not under Dev-Cpp, and the path of
it contains spaces or non-ascii characters.

This will be fixed in the next version.

For now, u can use mklink to make a symbolic link to your gcc folder in the
Dev-Cpp's folder.

dpx666 ***@***.***> 于2021年3月31日周三 下午12:50写道：
